### PR TITLE
Update faq.rst

### PR DESCRIPTION
**Pull request by imunro**
Err update the FAQ

### CODE REVIEW

**Comment by imunro** [comment]
@seanwarren No hurry on this one - but I'd like to get your thoughts.

**Comment by imunro** [comment]
@seanwarren If you have time could you have a look at this - in particular the bit on IRF shift needs some work as I'm not sure how/when it's safe to use - I'm trying to address the fact that people(well at Imperial & Beatson)  seem to think it must always be used

**Comment by seanwarren** [comment]
Hi Ian yes this a good point, I'll add a bit more detail tomorrow. Sorry must have missed the first notification

**Comment by imunro** [comment]
NP I only noticed when I went to add the recent stuff about G-Factors.

**Comment by imunro** [comment]
@seanwarren FYI  I put your recent e-mail about G factors in here as well.

**Pull request merged**
